# Generated by Django 5.0.3 on 2024-03-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaminatePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
