# Generated by Django 5.0.3 on 2024-03-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ish", "0002_laminateprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="saw",
            name="price",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="ish.laminateprice",
            ),
            preserve_default=False,
        ),
    ]
